version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 application/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    depends_on:
      - db
